version: "3.7"

services:
  cron-job:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: cron-job
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules